spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: mysql://localhost:13306/rabbitmq?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: root
    password: root
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
server:
  servlet:
    context-path: /
  port: 8002
mybatis:
  mapper-locations: classpath:mapping/*.xml
  logging:
    level:
      tk:
        mybatis: trace
  type-aliases-package: com.mirror95.rabbitmq.producer